version: "3.9"
services:
  api:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"
    networks: [net]

  nginx:
    image: nginx:1.27-alpine
    depends_on: [api]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks: [net]

networks:
  net:
    driver: bridge
